[tasks.docker-build]
script = '''
docker image build --tag mysql8-db-practice .
'''

[tasks.docker-run]
script = '''
docker container run \
  --platform linux/amd64 \
  --rm \
  --name mysql8-db-practice \
  -e MYSQL_ROOT_PASSWORD=rootpass \
  -p 3306:3306 \
  mysql8-db-practice
'''

[tasks.docker-stop]
script = '''
docker container stop mysql8-db-practice
'''

[tasks.docker-exec]
script = '''
docker container exec -it mysql8-db-practice bash
'''