name: Zola on Github Pages

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'notes/**'
  pull_request:

jobs:
  build:
    name: Build Site for PR
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Checkout main
        uses: actions/checkout@v3.0.0
      - name: Build Only
        # 最新版を利用する形式に変更
        uses: shalzz/zola-deploy-action@master
        env:
          BUILD_ONLY: true
          BUILD_FLAGS: --drafts
          # https://docs.github.com/ja/actions/security-guides/automatic-token-authentication
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  build-and-deploy:
    name: Build and Deploy to Github Pages
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout main
        uses: actions/checkout@v3.0.0
      - name: Build and Deploy
        uses: shalzz/zola-deploy-action@master
        env:
          # https://docs.github.com/ja/actions/security-guides/automatic-token-authentication
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
